name: easy ai

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy to VPS
      run: |
        # Add commands to deploy your project on the VPS
        # For example, you might use SSH to connect to your VPS and pull the latest changes
        ssh user@your-vps-ip 'cd /path/to/your/project && git pull origin main'

      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
